[package]
name = "trim_silence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minimp3 = "0.5"
dasp = "0.11"
dasp_sample = "0.11"
dasp_signal = "0.11"
clap = "2.33.3"
